# -*- coding: utf-8 -*-
"""Copy of Methane_Plume_Audit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyZDDQAmJ1utKHqf91sAzh2g4g0fobyE
"""

'''XAI-Methane-Tracker-Modeling-Satellite-Emissions-with-XGBoost-SHAP-and-Open-Meteo-APIs'''

# STEP: 1 PREPARING REAL-WORLD DATASET
import geopandas as gpd
import pandas as pd
import numpy as np
import requests
import time
import xgboost as xgb
import pickle
import shap
import os
import folium

print("=====================================================================")
print(" FIGURING OUT THE INDUSTRY CATEGORY BASED ON CLUES")
print("=====================================================================\n")

try:
    print("Ingesting local 'methane_metadata.geojson'...")
    gdf = gpd.read_file("methane_metadata.geojson", use_pyogrio=False)
    print(f"Successfully read {len(gdf)} raw NASA records!")
except Exception as e:
    print(f"ERROR: Could not read file. ({e})")
    exit()

advanced_records = []
waste_count = 0
oil_count = 0
target_limit = 20  # Gathering 40 total high-quality rows (20 per inferred sector) (Note : user can change this count no. as per their requirement, just change the target_limit value)

print("\n Running Rule-Based Spatial Classification Engine")

for idx, row in gdf.iterrows():
    if waste_count >= target_limit and oil_count >= target_limit:
        break
# Extracting geometric center (the centroid) coordinates for each plume
    centroid = row.geometry.centroid
    lon, lat = centroid.x, centroid.y

    concentration = row.get('Max Plume Concentration (ppm m)') or 2500.0
    date_observed = str(row.get('UTC Time Observed', '2023-10-15'))[:10]
    plume_id = row.get('Plume ID') or f"NASA_{idx}"

    # HEURISTIC SECTOR CLASSIFICATION
    # Segmenting our unlabeled data

    row_dump = " ".join([str(v).lower() for v in row.values])

    if "waste" in row_dump or "landfill" in row_dump or (concentration < 3200 and lat > 20.0):
        if waste_count >= target_limit: continue
        inferred_sector = "Waste_Landfill"
        waste_count += 1
    else:
        if oil_count >= target_limit: continue
        inferred_sector = "Oil_Gas_Energy"
        oil_count += 1

    print(f" Plume {plume_id} Classed As: [{inferred_sector}] (Lat: {lat:.2f}, Lon: {lon:.2f})")

    # Fetch Weather (the exact temperature (in Celsius) and wind speed (in km/h) at the precise moment the leak was spotted)

    weather_url = f"https://archive-api.open-meteo.com/v1/archive?latitude={lat}&longitude={lon}&start_date={date_observed}&end_date={date_observed}&hourly=temperature_2m,wind_speed_10m"

    try:
        w_response = requests.get(weather_url, timeout=10)
        w_data = w_response.json()
        temp = w_data["hourly"]["temperature_2m"][12]
        wind = w_data["hourly"]["wind_speed_10m"][12]

        advanced_records.append({
            "plume_id": plume_id,
            "sector_type": inferred_sector,
            "latitude": lat,
            "longitude": lon,
            "max_plume_conc_ppm_m": concentration,
            "historical_temp_c": temp,
            "historical_wind_kmh": wind
        })
        time.sleep(0.3)
    except Exception:
        continue

df_advanced = pd.DataFrame(advanced_records)
df_advanced.to_csv("Methane_Plume_data.csv", index=False)
print(f"\n SUCCESS: Generated 'advanced_multi_sector_data.csv' with balanced, inferred labels!")



# STEP: 2 TRAINING THE AI MODEL (XGBOOST)

print("=====================================================================")
print( "TRAINING THE ADVANCED XGBOOST BRAIN")
print("=====================================================================\n")

# Load the dataset gathered vy heuristic model
data_path = "Methane_Plume_data.csv"
if not os.path.exists(data_path):
    print(f"ERROR: Cannot find '{data_path}'. Run your parser script first!")
    exit()

df = pd.read_csv(data_path)
print(f"Successfully ingested {len(df)} balanced multi-sector rows.")

# Converting textual sectors into binary numeric flags
df_encoded = pd.get_dummies(df, columns=['sector_type'], dtype=int)

# Identify the columns we want the AI to learn from
feature_cols = ['historical_temp_c', 'historical_wind_kmh']
if 'sector_type_Waste_Landfill' in df_encoded.columns:
    feature_cols.append('sector_type_Waste_Landfill')
if 'sector_type_Oil_Gas_Energy' in df_encoded.columns:
    feature_cols.append('sector_type_Oil_Gas_Energy')

X = df_encoded[feature_cols]
y = df_encoded['max_plume_conc_ppm_m']

print(f"AI Training Features Configured: {feature_cols}")

# Initializing and training the model
model = xgb.XGBRegressor(
    n_estimators=120,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=1.0,
    random_state=42
)

print("Mapping decision splits across weather and industrial parameters...")
model.fit(X, y)
print("XGBoost Multi-Sector model fully optimized and trained!")

# Save the trained model binary
with open("advanced_methane_model.pkl", "wb") as f:
    pickle.dump(model, f)

# sTEP: 3 INITIALIZE SHAP TREE EXPLAINER

print("\n GENERATING DIGITAL AUDIT TRAIL (SHAP VALUES)...")
explainer = shap.TreeExplainer(model)
shap_values = explainer(X)

print("\n" + "="*75)
print(" EXECUTIVE ENVIRONMENTAL AUDIT REPORT")
print("="*75 + "\n")

# Print an in-depth look at how the model evaluates a few different entries
for idx, row in df.iterrows():
    if idx >= 6: # the first 6 from the dataset ( Note : Again this value is up to the user, to see the final audit report )
        break

    actual_concentration = row['max_plume_conc_ppm_m']
    sector = row['sector_type']
    temp = row['historical_temp_c']
    wind = row['historical_wind_kmh']

    print(f"RECORD #{idx+1} | ID: {row['plume_id']}")
    print(f" Sector Type : {sector}")
    print(f" Atmospheric Conditions : Temp: {temp}°C | Wind Speed: {wind} km/h")
    print(f" Methane Concentration    : {actual_concentration:.2f} ppm-m")
    print(f" SHAP ATTRIBUTION EVIDENCE:")

    # Map the contribution of each individual feature for this specific row
    for f_idx, col_name in enumerate(feature_cols):
        impact = shap_values.values[idx, f_idx]
        direction = "+" if impact >= 0 else ""

        # Dynamic Physical reasoning of the report
        reason = ""
        if col_name == 'historical_temp_c':
            if sector == "Waste_Landfill":
                if impact >= 0:
                    reason = f" High heat ({temp}°C) accelerates the biogenic rot/gas production."
                else:
                    reason = f" Relative lower temperature ({temp}°C) lowers the bacterial decay and gas release rates."
            else: # For Oil & Gas Sector
                if impact >= 0:
                    reason = f"High thermal profile ({temp}°C) expanded gas pressure or impacted flare efficiency."
                else:
                    reason = f"Thermal baseline drop ({temp}°C) reduced localized atmospheric pressure/venting intensity."

        elif col_name == 'historical_wind_kmh':
            if impact >= 0:
                reason = " Lower wind velocity/stagnant air traps the plume, creating high point concentration."
            else:
                reason = "Higher wind velocity dilutes and disperses the gas plume, lowering observed concentration."

        elif col_name == 'sector_type_Waste_Landfill':
            if impact >= 0:
                reason = "Baseline sector adjustment: Landfill classification added structural biogenic volume weight."
            else:
                reason = "Baseline sector adjustment: Landfill tag lowered expected baseline weight."

        elif col_name == 'sector_type_Oil_Gas_Energy':
            if impact >= 0:
                reason = "Baseline sector adjustment: High-pressure oil/gas asset profile raised emission scale baseline."
            else:
                reason = "Baseline sector adjustment: Asset classified away from high-pressure baseline benchmarks."

        # Print out the fully customized narrative string
        print(f"      • {col_name:<30} : {direction}{impact:>8.2f} ppm-m  | Reason: {reason}")

    print("-" * 75)

print("\n=====================================================================")
print("THE AI MODEL FINISHED TRAINING, AND THE RESULT HAVE BEEN SAVED SUCCESSFULLY")
print("=====================================================================")


# STEP: 4 PLOTTING METHANE LEAK POINTS ONTO AN INTERACTIVE GLOBAL MAP

# Ingest your processed multi-sector matrix
df = pd.read_csv("Methane_Plume_data.csv")

# Initialize an interactive map focused over coordinates
m = folium.Map(location=[df['latitude'].mean(), df['longitude'].mean()], zoom_start=4, tiles='OpenStreetMap')

# Plot every single inferred plume point automatically
for idx, row in df.iterrows():
    color = 'green' if row['sector_type'] == 'Waste_Landfill' else 'orange'
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=f"ID: {row['plume_id']}<br>Sector: {row['sector_type']}<br>Conc: {row['max_plume_conc_ppm_m']} ppm-m",
        icon=folium.Icon(color=color, icon='cloud')
    ).add_to(m)

# Save map array to an HTML viewer page
m.save("index.html")
print(" SUCCESS: Interactive map rendered!!!")